apiVersion: v1
kind: Service
metadata:
 annotations:
    fabric8.io/ingress.path: /alertmanager
    fabric8.io/ingress.annotations: |-
      ingress.kubernetes.io/rewrite-target: /
      ingress.kubernetes.io/force-ssl-redirect: true
      kubernetes.io/ingress.class: internal-ingress
  labels:
    app: grafana
    expose: "true"
  name: grafana
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: web
  selector:
    app: grafana
